version: '3.8' # 指定docker-compose的版本
services:
  # 数据库
  db:
    image: mysql:8 # 使用官方mysql8的镜像
    container_name: blog # 容器名称
    restart: always # 容器异常退出时自动重启
    # 配置MYSQL环境变量
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # root用户密码
      MYSQL_DATABASE: blog # 容器启动时自动创建数据库blog
      # MYSQL_USER: bloguser # 普通用户
      # MYSQL_PASSWORD: blogpass # 普通用户密码
    ports:
      - '3306:3306' # 把容器的3306端口映射到本机的3306端口
    # 数据持久化.把MYSQL数据存储到宿主机,避免容器删掉后数据丢失
    volumes:
      - blog-mysql-data:/var/lib/mysql

  # redis
  redis:
    image: redis:7 # 使用官方redis7镜像
    container_name: redis # 容器名称
    ports:
      - '6379:6379' # 把容器的6379端口映射到本机的6379端口

volumes:
  blog-mysql-data: # 卷, 用于MYSQL数据持久化
